# Generated by Django 4.2.21 on 2025-05-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_tag_post_image_name_post_author_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email_address',
            new_name='email',
        ),
    ]
